version: "3.5"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: todotask
      MYSQL_USER: todo
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/frontend
      - /usr/front/node_modules
    ports:
      - 8000:8080
    environment:
      - PORT=8080
      - NODE_ENV=development
      - BACK_END=backend
  backend:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - frontend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/todotask?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
