version: "3.5"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: todotask
      MYSQL_ROOT_PASSWORD: 1234
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS operation;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/frontend
      - /usr/front/node_modules
    ports:
      - 8000:8080
    environment:
      - PORT=8080
      - NODE_ENV=development
      - BACK_END=backend
  backend:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - frontend
    restart: always
    environment:
      - SPRING_FIRST-DATASOURCE_JDBCURL=jdbc:mysql://mysql/todotask?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_FIRST-DATASOURCE_USERNAME=root
      - SPRING_FIRST-DATASOURCE_PASSWORD=1234
      - SPRING_SECOND-DATASOURCE_JDBCURL=jdbc:mysql://mysql/operation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_SECOND-DATASOURCE_USERNAME=root
      - SPRING_SECOND-DATASOURCE_PASSWORD=1234
