
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todotask?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

jwt:
  secret:
    key: z#D%D*G-KaPdSgTkYp1s5v8y/B?E(H+M